#!/usr/bin/env node
/**
 * Completes the first-run setup wizard against a freshly-booted Jellyfin container (no
 * hardcoded credentials — the wizard assigns a fresh admin account per run, mirroring
 * tests/Jellyfin.Server.Integration.Tests/AuthHelper.cs's CompleteStartupAsync), registers a
 * real library pointing at ../fixtures (tiny synthetic media generated by generate-fixtures.sh),
 * triggers a scan, and waits for it to finish.
 *
 * Usage: node seed.js <baseUrl> <expectedItemCount>
 * Prints { baseUrl, accessToken, userId, serverId, itemCount } as JSON on stdout.
 */

const baseUrl = process.argv[2];
const expectedItemCount = parseInt(process.argv[3] ?? '0', 10);

if (!baseUrl) {
  console.error('Usage: node seed.js <baseUrl> <expectedItemCount>');
  process.exit(1);
}

const AUTH_HEADER = 'MediaBrowser Client="Jellyfin PerfTest Layer3", Device="PerfTest", DeviceId="perf-layer3-seed", Version="10.10.3"';

async function api(path, opts = {}) {
  const res = await fetch(`${baseUrl}${path}`, {
    ...opts,
    headers: { 'Content-Type': 'application/json', ...(opts.headers || {}) },
  });
  if (!res.ok) {
    throw new Error(`${opts.method || 'GET'} ${path} -> ${res.status} ${await res.text()}`);
  }
  return res;
}

async function completeStartup() {
  // Same three calls as AuthHelper.CompleteStartupAsync (tests/Jellyfin.Server.Integration.Tests):
  // GET the wizard-assigned default admin user, POST to finalize the wizard, then authenticate.
  const userRes = await api('/Startup/User');
  const user = await userRes.json();

  await api('/Startup/Complete', { method: 'POST' });

  const authRes = await api('/Users/AuthenticateByName', {
    method: 'POST',
    headers: { Authorization: AUTH_HEADER },
    body: JSON.stringify({ Username: user.Name, Pw: user.Password }),
  });
  const auth = await authRes.json();
  return auth.AccessToken;
}

async function ensureLibrary(token, name, path) {
  const authed = (opts = {}) => ({ ...opts, headers: { ...(opts.headers || {}), Authorization: `${AUTH_HEADER}, Token="${token}"` } });

  await api(
    `/Library/VirtualFolders?name=${encodeURIComponent(name)}&collectionType=movies&refreshLibrary=false&paths=${encodeURIComponent(path)}`,
    authed({ method: 'POST' }),
  );

  const listRes = await api('/Library/VirtualFolders', authed());
  const folders = await listRes.json();
  const folder = folders.find((f) => f.Name === name);
  if (!folder) throw new Error(`Library "${name}" not found after creation`);
  return folder;
}

async function waitForScan(token, expected, timeoutMs = 60000) {
  const authed = { headers: { Authorization: `${AUTH_HEADER}, Token="${token}"` } };
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const res = await api('/Items?Recursive=true&IncludeItemTypes=Movie&Limit=1', authed);
    const body = await res.json();
    if (body.TotalRecordCount >= expected) return body.TotalRecordCount;
    await new Promise((r) => setTimeout(r, 1000));
  }
  throw new Error(`Scan did not surface ${expected} items within ${timeoutMs}ms`);
}

(async () => {
  const token = await completeStartup();

  const meRes = await fetch(`${baseUrl}/Users/Me`, {
    headers: { Authorization: `${AUTH_HEADER}, Token="${token}"` },
  });
  const me = await meRes.json();

  // jellyfin-web's client-side connection handshake checks the stored server id against the
  // live server's actual one — a placeholder id here left the SPA stuck pre-render (confirmed:
  // navTime hit the same ~timeout ceiling on every page/run regardless of branch, until fixed).
  const infoRes = await fetch(`${baseUrl}/System/Info/Public`);
  const info = await infoRes.json();

  await ensureLibrary(token, 'PerfTestMovies', '/fixtures');

  await api('/Library/Refresh', {
    method: 'POST',
    headers: { Authorization: `${AUTH_HEADER}, Token="${token}"` },
  });

  const found = await waitForScan(token, expectedItemCount);

  process.stdout.write(JSON.stringify({ baseUrl, accessToken: token, userId: me.Id, serverId: info.Id, itemCount: found }));
})().catch((err) => {
  console.error(err.stack || err.message);
  process.exit(1);
});
